# Basic `dependabot.yml` file with

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
      - "gha"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      gh-actions:
        patterns:
          - "actions/*"
          - "github/*"
      aws-actions:
        patterns:
          - "aws-actions/*"
      docker-actions:
        patterns:
          - "docker/*"
    reviewers:
      - emargetis
      - taraspos
      - ptgott

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    labels:
      - "dependencies"
      - "nodejs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    groups:
      docusaurus:
        patterns:
          - &docusaurus "@docusaurus/*"
      inkeep:
        patterns:
          - &inkeep "@inkeep/*"
      postcss:
        patterns:
          - &postcss "*postcss*"
      npm-web-dependencies:
        # Catch-all for minor/patch Web deps, but explicitly exclude Docusaurus
        patterns:
          - "*"
        exclude-patterns:
          - *inkeep
          - *docusaurus
          - *postcss
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - emargetis
      - ptgott
