name: Docs Preview
on:
  pull_request:
  merge_group:

permissions:
  pull-requests: write
  id-token: write

jobs:
  amplify-preview:
    if: ${{ github.event_name != 'merge_group' }}
    name: Amplify Preview
    runs-on: ubuntu-22.04-2core-arm64
    environment: docs-amplify
    steps:
    - name: Get runtime values from kvstore
      id: kvstore
      uses: gravitational/shared-workflows/tools/env-kvstore@tools/env-kvstore/v1.0.3
      with:
        cognito-identity-pool-id: "us-west-2:da53389e-a459-4a28-bd54-43eeb8e4b579"
        cognito-role-arn: "arn:aws:iam::247230412011:role/github-actions-cognito-oidc"
        values: |
          IAM_ROLE,variable
          AMPLIFY_APP_IDS,variable

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        aws-region: us-west-2
        role-to-assume: ${{ env.IAM_ROLE }}

    - name: Get Amplify Preview URL
      uses: gravitational/shared-workflows/tools/amplify-preview@986f92841a4f032e262477e5bb15f214d50b1015 # tools/amplify-preview/v0.0.6
      id: amplify_preview
      with:
        app_ids: ${{ env.AMPLIFY_APP_IDS }}
        create_branches: "false"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        wait: "true"
        wait_interval: 60s

    - name: Print failure message
      if: failure()
      env:
        ERR_TITLE: Teleport Docs preview build failed
        ERR_MESSAGE: >-
          Please refer to the following documentation for help: https://www.notion.so/goteleport/How-to-Amplify-deployments-162fdd3830be8096ba72efa1a49ee7bc?pvs=4.
          Execution info: ${{ steps.amplify_preview.outputs.amplify_app_id }} ${{ steps.amplify_preview.outputs.amplify_branch_name }} ${{ steps.amplify_preview.outputs.amplify_job_id }}
      run: |
        echo ::error title=$ERR_TITLE::$ERR_MESSAGE
        exit 1

  # If the event is merge_group, we want to make sure the build passes with the
  # most recent version of the docs content to prevent unexpected inputs from
  # breaking the build. Execute a local build on the GitHub Actions runner
  # without a preview link.
  local-preview:
    if: ${{ github.event_name == 'merge_group'}}
    name: Amplify Preview
    runs-on: ubuntu-22.04-4core-arm64
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install deps
        run: yarn

      - name: Cache tarball downloads
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .downloads/
          key: tarball-downloads-${{ hashFiles('config.json') }}
          restore-keys: tarball-downloads-

      - name: Build the docs with the latest content
        run: yarn build

      # Prevent a change in the linter from failing on unexpected docs content
      # changes.
      - name: Run the docs formatting linter
        run: yarn markdown-lint

      - name: Check config.json
        run: scripts/validate-docs-config.sh
