name: Dependency Review

on:
  pull_request:

jobs:
  dependency-review:
    uses: gravitational/shared-workflows/.github/workflows/dependency-review.yaml@main
    permissions:
      contents: read
    with:
      allow-additional-licenses: >
        LicenseRef-scancode-public-domain AND Unlicense
      allow-dependencies-licenses: >
        pkg:npm/%40inkeep/cxkit-color-mode,
        pkg:npm/%40inkeep/cxkit-primitives,
        pkg:npm/%40inkeep/cxkit-react,
        pkg:npm/%40inkeep/cxkit-styled,
        pkg:npm/%40inkeep/cxkit-theme,
        pkg:npm/%40inkeep/cxkit-types,
        pkg:npm/domain-browser
